### ISSUE TITLE
Can't get a certain URL (always receive no content)

### ISSUE THREAD

**Issue by SirVer** [sagebind/isahc#140]
This is related to https://github.com/http-rs/surf/issues/117 where I found that `https://www.spiegel.de/schlagzeilen/index.rss` never gives me back what I expect. @tirr-c identified that the problem is not due to surf, but reproducible with isahc.

Here is the original issue reported to surf:

~~~
Using `surf 1.0.3` from crates.io, rustc 1.39.0 (4560ea788 2019-11-04) on Mac OS and this program:

```rust
#[async_std::main]
async fn main() {
    env_logger::init();    
    let rv = surf::get("https://www.spiegel.de/schlagzeilen/index.rss")
        .recv_bytes()
        .await;
    match rv {
        Ok(_) => (),
        Err(e) => println!("{:?}", e),
    }
}
```

I get 100% of the time `NoResponse` as error. However if I do `curl 'https://www.spiegel.de/schlagzeilen/index.rss'` on the commandline or use `reqwest` with tokio equivalently, I do get the expected content.

I tried using the `hyper-client` feature, but unfortunately that did not compile for me.
~~~

And here is the comment that claims this problem reproduces with isahc: https://github.com/http-rs/surf/issues/117#issuecomment-562198460.

**Comment by sagebind** [comment]
(Copy-pasted example here for context)

```rust
use isahc::prelude::*;

fn main() {
    let body = Body::reader([].as_ref());
    let request = Request::get("https://www.spiegel.de/schlagzeilen/index.rss").body(body).unwrap();
    let result = isahc::send(request);
    match result {
        Err(e) => println!("{:?}", e),
        Ok(_) => {},
    }
}
```

I believe the issue here is that [`Body.is_empty`](https://docs.rs/isahc/0.8.2/isahc/prelude/struct.Body.html#method.is_empty) is returning `false` here, which Isahc then correctly assumes that a request body is intended to be sent. If you do not want to send a request body (regardless of the HTTP method), then you should construct a body where `Body.is_empty` returns `true` instead. There are multiple ways of doing this, but of course `Body::empty()` is the easiest.

**Comment by SirVer** [comment]
@sagebind Thanks! Closing this as the problem lies within surf then.
