### ISSUE TITLE
Empty body does not set content-length header

### ISSUE THREAD

**Issue by Hawk777** [sagebind/isahc#144]
If I send a POST request with a nonempty body (say a simple byte slice), then in `create_easy_handle`, `has_body` is true, `body_length` is the length of the body, and then the `Content-Length` header is set (via the `post_field_size`).

If I send a POST with an empty body, then `has_body` is false, and the `Content-Length` header is not set. It seems to me that, if the request method is one that permits a body at all, then `Content-Length` should always be set if the body length is known, including if the known value happens to be zero.

**Comment by sagebind** [comment]
Based on the RFC info here: https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.3

We should have a clear distinction between a zero-length body and no body. If an explicit body is given (even zero-length), then we should include a `Content-Length` request header. But if there is no request body (as opposed to a zero-length one) then `Content-Length` should _not_ be included. The request method should be irrelevant here.

The short-term fix would be to change `Body::is_empty` to be `self.0 == Inner::Empty` instead of looking at the length.

I'm not totally happy with our current API for the request body, as the distinction between no body and a zero-length one is too implicit. I haven't thought through yet what a better API would look like but I am open to feedback.

**Comment by Hawk777** [comment]
Sorry I didn’t get back to this for a bit. I don’t think the request method is irrelevant. The very section you linked to says, “A message-body MUST NOT be included in a request if the specification of the request method (section 5.1.1) does not allow sending an entity-body in requests.” Either way, though, I think your fix is fine, because it basically leaves it up to the user to get things right (i.e. to use `empty()` for places where they don’t want a body at all, or an empty array if they do).

Maybe “An empty body will have a known length of 0 bytes.” (the comment on the `empty()` function) is a little bit misleading now, since the thing returned by that function isn’t any more just a zero-byte-long body, it’s actually *no* body?

**Comment by sagebind** [comment]
Yeah, GET requests for example are not supposed to have a request body, but the `http::Request` type does not have that as part of the contract. And sometimes people _do_ need to make strange requests (perhaps to legacy APIs that do not follow the spec) so I'd like to still leave the option available.

Agreed, the verbage of `Body::empty` is confusing. I will update it.
