### ISSUE TITLE
isahc::Body is !Sync

### ISSUE THREAD

**Issue by yoshuawuyts** [sagebind/isahc#172]
Hi! In order to fix https://github.com/http-rs/surf/issues/97 and other issues, we've been working on [a new set of libraries](https://blog.yoshuawuyts.com/async-http/), including [http-types](https://docs.rs/http-types). One feature this includes is that the `Body` type implements `Send + Sync`.

However as we've started migrating to `http-types` (https://github.com/http-rs/http-client/pull/22), we've noticed that `isahc::Body` is `!Sync`. We were wondering if it'd be possible to change this? Thanks heaps!

**Comment by sagebind** [comment]
Seems reasonable to me. The only thing preventing it from being `Sync` currently is that you are allowed to create a `Body` from an `AsyncRead` that doesn't implement `Sync`, but this is probably very uncommon. Since this is a breaking change, we can add the additional restriction in the 0.9 release.

**Comment by yoshuawuyts** [comment]
@sagebind that would be fantastic, thanks heaps!

**Comment by sagebind** [comment]
This change is now available in the [0.9](https://github.com/sagebind/isahc/releases/tag/0.9.0) release!
