### ISSUE TITLE
Additional cookie features

### ISSUE THREAD

**Issue by Anonymus1** [sagebind/isahc#215]
Allow reading of current stored cookies with something like a client.get_cookies() function.

**Comment by sagebind** [comment]
It may also be nice to expose the cookie parsing capability without necessarily enabling the cookie jar, so that you could do something like `response.cookies()` to inspect the parsed results of `Set-Cookie` headers, and something like `request.cookies_mut().insert(cookie)` to add a custom `Cookie` header in a more convenient way.

We'll have to expose some details of the `Cookie` struct in the API for these additions to work. Currently the struct members are all private with no public methods. The [cookie](https://crates.io/crates/cookie) crate has matured quite a bit since when cookies were first implemented in Isahc. We might be able to borrow or re-use that crate's API a bit here.

**Comment by sagebind** [comment]
A minimal API for this is now available in the [0.9.11 release](https://github.com/sagebind/isahc/releases/tag/0.9.11)! It is limited to the basics of accessing cookies in the cookie jar by URI and name, though in the future we can expand the API to do more things, such as creating and persisting artificial cookies, getting cookie attributes, etc.
