### ISSUE TITLE
Please document the minimum supported rust version (MSRV)

### ISSUE THREAD

**Issue by rbtcollins** [sagebind/isahc#219]
Just had ISAHC failing in CI with:
```rust
error: attributes are not yet allowed on `if` expressions
##[error]   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/isahc-0.9.7/src/config/dial.rs:137:9
    |
137 |         #[cfg(unix)]
    |         ^^^^^^^^^^^^

error: aborting due to previous error
##[error]aborting due to previous error
error: could not compile `isahc`.
```

That was with 1.42, and we try to keep track of the lowest version of rust that things are known to build with :). I see there is a ticket for making a 1.0, presumably fixing the MSRV at that point will be important too.

**Comment by sagebind** [comment]
That is correct, as stated on the readme [here](https://github.com/sagebind/isahc#supported-rust-versions):

> The current release is only guaranteed to work with the latest stable Rust compiler. When Isahc reaches version `1.0`, a more conservative policy will be adopted.

The next non-patch release [is planned to be 1.0](https://github.com/sagebind/isahc/issues/25). I will add a note there to remember to pin the MSRV at that point as well.

**Comment by alexliesenfeld** [comment]
I wonder why a patch version breaks existing builds? It should have been released as a minor version instead. As cargo follows semver, patch versions are automatically upgraded and break existing code. Please compare to https://semver.org/#spec-item-6 .

**Comment by sagebind** [comment]
My mental model for patch versions is that no API changes are made, and for minor versions only backwards-compatible API changes are made. I didn't think about (nor intentionally change) the minimum Rust version required, my bad.

Though also it is a bit odd, because Isahc is currently on 0.x, so by Cargo's modified semver rules, a "minor" version is essentially a major version and a "patch" version is essentially a minor version. I think a lot of confusion comes around the prolific use of version 0 in the Rust ecosystem, which I'm slowly changing my mind about. Isahc probably should have been 1.x a long time ago...

**Comment by sagebind** [comment]
Isahc will now compile with Rust 1.41+ as of #259, and this will be the official MSRV policy for the soon-to-be Isahc 1.0.
