### ISSUE TITLE
How to optimize isahc performance?

### ISSUE THREAD

**Issue by flyinmind** [sagebind/isahc#242]
I use isahc to realize a simple http bench mark tool.
The http server runs on actix-web v3.1.0. Rust version is 1.47.
Client and server are all in the same machine.
Windows 10 system, intel 8 cores 1.6Ghz, and 8G mem.

Use isahc,thread-num:8,use-time:12388 ms,speed:12915, **About 13000/s** , the tool occupies **30%+** CPU , server about **12%CPU.**
On the same server, use **baton** (a tool by go), **about 40000/s**, it occupies **15% CPU** , server 15% CPU.

It is a very simple condition. Isahc performances not well.
**Anybody knows Why? And how to optimize it?** Thanks!
I tried sync/async get, both are bad :(

Thanks!

Comile  command: **cargo run --release**, and profile is:
codegen-units = 8
codegen-threads=8
#debug = true
lto = true
overflow-checks = true
opt-level = 3

**### Code:**
```
//--------------------------------------------------------------------------------------------------
use isahc::prelude::*;
use isahc::HttpClient;
use isahc::config::{ResolveMap, DnsCache};
use async_std::*;
use std::time::{SystemTime, Duration};

const threadNum : usize = 8;
const runTimes : u64 = 20000;

#[async_std::main]
async fn main() -> Result<(), isahc::Error> {
    // Send a GET request and wait for the response headers.
    // Must be `mut` so we can read the response body.
    let start = SystemTime::now();
    let mut i : usize = 0;
    //let sys = actix::System::new("test");
    let mut handlers = vec![];

    while i < threadNum {
        i += 1;
        let no = i;
        let h = task::spawn(async move {
            let client = HttpClient::builder()
                .max_connections(10)
                .max_connections_per_host(10)
                .connection_cache_size(10)
                .tcp_keepalive(Duration::from_secs(10))
                .dns_cache(DnsCache::Forever)
                //.dns_resolve(ResolveMap::new()
                // Send requests for example.org on port 80 to 127.0.0.1.
                //.add("www.example.org", 8080, [127, 0, 0, 1]))
                .build().unwrap();

            let mut i : u64 = 0;
            while i < runTimes {
                i += 1;
                let mut response = client.get_async("http://127.0.0.1:8080/").await.unwrap();
                // Print some basic info about the response to standard output.
                // println!("Status: {}", response.status());
                // println!("Headers: {:#?}", response.headers());
                response.text_async().await.unwrap();
                // // Read the response body as text into a string and print it.
                // print!("{}-{},{}",no, i, response.text().unwrap());
            }
        });
        handlers.push(h);
    }
    for h in handlers {
        h.await;
    }

    let interval = start.elapsed().unwrap().as_millis() as u64;

    println!("thread-num:{},use-time:{} ms,speed:{}", 
        threadNum, interval, runTimes * 1000 * (threadNum as u64) / interval);

    Ok(())
}
```

**Comment by sagebind** [comment]
Thanks for taking the time to create this issue! I always love to see how people are using Isahc in the real world, and learning how I can make it better.

I'll take a deeper investigation into your code sometime later when I have more time, but at first glance here's what I noticed:

- You might get better connection re-use if you use just one client wrapped in an `Arc` from your parallel tasks.
- `text_async` could waste a lot of CPU cycles if you don't need it. It attempts to detect the text encoding of the response body, decodes it, allocates a big string, and then converts the text into UTF-8 and writes it to the string, and returns it. This is the desired behavior of that method, but if you are benchmarking, it is probably an unnecessary step. Just drain the response body into a [`sink`](https://docs.rs/async-std/1.6.5/async_std/io/fn.sink.html) instead.
  - Note: You are right to read the response body to the end though; due to the nature of HTTP if you simply drop the response without completely reading the body the connection can't be re-used. Though depending on the size of the response body, simply not reading it and paying the cost of new connections might be worth it, depending on if you are using HTTP/2 or not.
- You're running on Windows. Isahc unfortunately has sub-optimal throughput there because libcurl is using `select()` under the hood, which has especially poor scalability on Windows. For normal day-to-day usage you're unlikely to notice the difference, but in a benchmarking tool it could definitely be noticeable. This is noted in #17 which I've re-opened, since I finally have an idea on how to make it better.

**Comment by flyinmind** [comment]
Thanks for your attention!
After removing the line "response.text_async().await.unwrap();"
no improvement.
Baton and isahc all run on the same server. I have not study the difference between libcurl and Go's realization.
I tried actix-web-client, hyper-client,reqwest, they are all worse than baton.
It lets me disappointed. I think rust should the No.1 :(

I like comparing performance among different libs before deciding to use it.
Very bad habit, makes me tied :(

**Comment by flyinmind** [comment]
Server code, with actix-web.
Cargo.toml
[dependencies]
actix-web = "*"

```
use actix_web::{get, middleware, web, App, HttpRequest, HttpResponse, HttpServer};

#[get("/resource1/{name}/index.html")]
async fn index(req: HttpRequest, name: web::Path<String>) -> String {
    println!("REQ: {:?}", req);
    format!("Hello: {}!\r\n", name)
}

async fn index_async(req: HttpRequest) -> &'static str {
    println!("REQ: {:?}", req);
    "Hello world!\r\n"
}

#[get("/")]
async fn no_params() -> &'static str {
    "Hello world!\r\n"
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    //std::env::set_var("RUST_LOG", "actix_server=info,actix_web=info");
    //env_logger::init();

    HttpServer::new(|| {
        App::new()
            .wrap(middleware::DefaultHeaders::new().header("X-Version", "0.2"))
            .wrap(middleware::Compress::default())
            .wrap(middleware::Logger::default())
            .service(index)
            .service(no_params)
            .service(
                web::resource("/resource2/index.html")
                    .wrap(
                        middleware::DefaultHeaders::new().header("X-Version-R2", "0.3"),
                    )
                    .default_service(
                        web::route().to(|| HttpResponse::MethodNotAllowed()),
                    )
                    .route(web::get().to(index_async)),
            )
            .service(web::resource("/test1.html").to(|| async { "Test\r\n" }))
    })
    .bind("127.0.0.1:8080")?
    .workers(1) //**if set to 8, isahc reaches 18000/s, baton reaches 70000/s**
    .run()
    .await
}
```

**Comment by flyinmind** [comment]
Test on my home PC, windows 10, intel 8 cores, 1.6Ghz, 8G mem.
VertX + baton ==> 65000/s
VertX + Isahc ==> 25000/s
Actix-Web(8 workers) + baton ==> 70000/s
Actix-Web(8 workers) + Isahc ==> 18000/s

Vertx server's code is copied from https://vertx.io/, no any optimization.
Server and client are all run in the same PC.
```
package vertx;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Vertx;

public class ServerTest extends AbstractVerticle {
    private static Vertx vertx = Vertx.vertx();

    // Convenience method so you can run it in your IDE
    public static void main(String[] args) throws Exception {
        vertx.deployVerticle(new ServerTest());
    }

    @Override
    public void start() throws Exception {
        vertx.createHttpServer().requestHandler(req -> {
            req.response().putHeader("content-type", "text/html").end("Hello world");
        }).listen(8080);
    }
}
```

**Comment by sagebind** [comment]
Could you do me a favor and test out #243 for me? I'd like to see if that gives better performance for you. I have a suspicion that it will, but I'm not sure by how much.

You can test out that pull request by specifying the repo and branch name in your dependencies instead of the Isahc version, like this:

```toml
[dependencies]
isahc = { git = "https://github.com/sagebind/isahc", branch = "better-polling" }
```

**Comment by flyinmind** [comment]
It is my pleasure.

On my PC, windows 10, intel 1.6Ghz
It doesn't work. The process is idle. Maybe it was blocked.
Client instance is moved out of while.
Before updating isahc, it's ok. 

```
use isahc::prelude::*;
use isahc::HttpClient;
use isahc::config::{ResolveMap, DnsCache};
use async_std::*;
use std::sync::Arc;
use std::time::{SystemTime, Duration};

const threadNum : usize = 8;
const runTimes : u64 = 20000;

#[async_std::main]
async fn main() -> Result<(), isahc::Error> {
    // Send a GET request and wait for the response headers.
    // Must be `mut` so we can read the response body.
    let start = SystemTime::now();
    let mut i : usize = 0;
    let mut handlers = vec![];
    let client = HttpClient::builder()
        .max_connections(20)
        .max_connections_per_host(20)
        .connection_cache_size(20)
        .tcp_keepalive(Duration::from_secs(20))
        .dns_cache(DnsCache::Forever)
        //.dns_resolve(ResolveMap::new()
        // Send requests for example.org on port 80 to 127.0.0.1.
        //.add("www.example.org", 8080, [127, 0, 0, 1]))
        .build().unwrap();

    let clientPtr = Arc::new(client);

    while i < threadNum {
        i += 1;
        let no = i;
        let c = clientPtr.clone();

        let h = task::spawn(async move {
            let mut i : u64 = 0;
            while i < runTimes {
                i += 1;
                let mut response = c.get_async("http://127.0.0.1:8080/").await.unwrap();
                // Print some basic info about the response to standard output.
                // println!("Status: {}", response.status());
                // println!("Headers: {:#?}", response.headers());
                //response.text_async().await.unwrap();
                // // Read the response body as text into a string and print it.
                // print!("{}-{},{}",no, i, response.text().unwrap());
            }
        });
        handlers.push(h);
    }
    for h in handlers {
        h.await;
    }

    let interval = start.elapsed().unwrap().as_millis() as u64;

    println!("thread-num:{},use-time:{} ms,speed:{}", 
        threadNum, interval, runTimes * 1000 * (threadNum as u64) / interval);

    Ok(())
}
```

**Comment by flyinmind** [comment]
I don't know whether the link helpful or not?
https://github.com/http-rs/surf/issues/143

**Comment by sagebind** [comment]
That issue does not look relevant, that issue is complaining that Surf is slower than Isahc proper for a single request, but Isahc itself is not slow. Here, the issue is that Isahc's throughput is acceptable, but less than desirable and has room for improvement.

I hope to take a deeper look into this issue sometime this week; I am usually unavailable during the weekend.

**Comment by sagebind** [comment]
@flyinmind Could you try testing the branch in #243 again? I've ironed out a couple bugs that were likely causing hangs on Windows.

**Comment by flyinmind** [comment]
still hang on

**Comment by sagebind** [comment]
OK, so there are some minor performance improvements that I am currently working on, and now that I have a proper profiling setup going I can go into a bit more detail. But it would be fair to say that Isahc isn't going to triple its performance overnight, since "make it go faster" is a pretty difficult thing to do, unless something in particular is going wrong here.

As far as #243 goes, it seems it is still quite a ways off from being ready to use yet, and based on my analysis it seems like that could deliver maybe a 9% speedup (at least on my machine), once it is working properly (IOCP seems to be a fickle beast).

On my machine anyway, here's where it seems the time is being spent (approximately):

- 58% waiting on [`getsockopt`](https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-getsockopt)
  - I'm not really sure why this is happening, I'll look into it. It is possible that `Connection: keep-alive` isn't happening though as I would expect a TCP connection to get continually reused.
- 9% writing buffers to sockets. Not much to do about this.
- 7% spent on waking async-std task wakers, not sure why this is exactly but seems like maybe an optimization problem with async-std
- 6% polling for socket I/O
  - 3% is done in a silly manner that could easily be removed once #243 is implemented. What curl is doing is, after a socket is ready to send or receive data, curl is calling `select()` _again_ because it doesn't know which it is ready for (send/receive). In #243 we tell curl which it is directly and make this unnecessary.
- 4% creating socket handles
- 2% spent on gzip decoding (Actix Web is compressing its response with gzip)
- 1% parsing URLs

**Comment by flyinmind** [comment]
I think it is a great study.
I hope that libcurl and async-std know the result and try to optimize it.
