### ISSUE TITLE
Why there's no `json_async`?

### ISSUE THREAD

**Issue by AurevoirXavier** [sagebind/isahc#245]
Something like `text_async`.

**Comment by sagebind** [comment]
Primary reason is there's not an ideal way of implementing it; ideally, Serde would support async deserialization so that we could incrementally decode the response body as bytes become available, but last I checked this was not supported. The only way it could be implemented would be to read the response body into a vec all at once (asynchronously), and then deserialize from that.

Perhaps we could follow that implementation anyway and add a disclaimer on the method that the entire response body will be held in memory.

**Comment by AurevoirXavier** [comment]
How this works? https://docs.rs/surf/2.1.0/surf/struct.Response.html#method.body_json

**Comment by sagebind** [comment]
Looks like that reads the entire response body into memory as well.

**Comment by sagebind** [comment]
This is now available in the [1.1.0 release](https://github.com/sagebind/isahc/releases/tag/1.1.0)!
