### ISSUE TITLE
Question: Is it possible to avoid binding a UDP socket?

### ISSUE THREAD

**Issue by kjvalencik** [sagebind/isahc#263]
https://github.com/sagebind/isahc/blob/5b17d4c13b1c2140a75920eca3b3609011d7084c/src/agent.rs#L76

It might be outside the scope of this project, but I'm attempting to use `isahc` in a macOS app with sandboxing enabled. Since `isahc` creates a UDP socket, it requires the _server_ entitlement even when I only need to make client requests.

It would be nice if this could be achieved without a socket or if concurrency was feature flagged.

**Comment by sagebind** [comment]
Thanks for filing an issue! I'm always happy to accept feedback such as this. The use of UDP is unfortunate here, as it is the only cross-platform way to interrupt a `select(2)` call which is how Isahc does its I/O asynchronously. We could use a UNIX pipe instead of UDP on Linux and macOS without too much trouble though.

That said, I'm already working on getting rid of the UDP socket completely in #243, by replacing `select(2)` altogether with a different I/O driver that supports wakeups natively. I'm not sure what the timeline on that PR is though since finicky IOCP bits on Windows has been causing some trouble so far, though hopefully it will be ready by the end of the year.

**Comment by kjvalencik** [comment]
@sagebind That's awesome! `isahc` is fantastic and I would love to be able to use it in my cross platform app. Unfortunately, requiring the server entitlement on Apple isn't an option because it would be denied by the app store. Let me know if there's anything I can do to help. 😁  Cheers!

**Comment by sagebind** [comment]
This is now fixed in the [1.2.0 release](https://github.com/sagebind/isahc/releases/tag/1.2.0)! Sorry about the delay, as this required a significant refactoring. Better late than never I suppose?

**Comment by kjvalencik** [comment]
Awesome! Thanks so much @sagebind!
