### ISSUE TITLE
failed to write response body because the response reader was dropped

### ISSUE THREAD

**Issue by MCOfficer** [sagebind/isahc#270]
When doing a lot of very similar requests, occasionally i will get logs like this:

```
[WARN] failed to write response body because the response reader was dropped
```

I know these are just warnings, but I'm currently debugging a tricky problem and I'd rather be sure about what is happening. Why are these warnings happening, and is there any way to prevent them?

Here's the code in question:

```rust
    let response = isahc::http::Request::put(format!("{}/links/_bulk", opt.elastic_url))
        .header(CONTENT_TYPE, "application/json")
        .authentication(Authentication::basic())
        .credentials(Credentials::new("elastic", opt.elastic_pass.clone()))
        .body(body.to_string())?
        .send()?;
    if !response.status().is_success() {
        let mut buffer = String::new();
        response.into_body().read_to_string(&mut buffer)?;
        error!("Got non-success status code, response was\n {}", buffer);
    }
```

Is this perhaps due to `into_body` consuming the response?

**Comment by sagebind** [comment]
Interesting, this should probably not be happening for code like the above. This warning is emitted if you drop the reponse `Body` without first reading from it fully, such as in code like this:

```rust
let response = isahc::get("http://some/url");
let _body = response.into_body();
// We just dropped _body without reading from it
```

This is a warning because it is a perfectly valid thing to do if you want to, but for most HTTP versions this means the connection must be closed and can't be reused for connection pooling, resulting in sub-optimal throughput.

However, if the only thing using the HTTP client is your code example, then `read_to_string` should be consuming the response body fully, so I would not expect to see this warning unless something else is going on.

What's the value returned by `isahc::version()`, just so I know how Isahc is built and configured?

**Comment by MCOfficer** [comment]
> What's the value returned by `isahc::version()`, just so I know how Isahc is built and configured?

```isahc/0.9.12 (features:default,encoding_rs,http2,mime,static_curl,text_decoding) libcurl/7.73.0-DEV OpenSSL/1.1.1h zlib/1.2.11 nghttp2/1.33.90
```

This is the output from my development machine. By my understanding it should be the same on my production server (thanks to `Cargo.lock` and the `static-curl` feature), but if you want I can retrieve the `isahc::version` from my server, too.

**Comment by MCOfficer** [comment]
From my server:
```
isahc/0.9.12 (features:default,encoding_rs,http2,mime,static_curl,text_decoding) libcurl/7.73.0
-DEV OpenSSL/1.1.1 zlib/1.2.11 nghttp2/1.33.90
```

I should note that these are extremely rare - i make about 35k requests, and last time i got 4 warnings, probably when the server just fails for whatever reason. I'll try and print more diagnostics when it happens.

**Comment by sagebind** [comment]
Thanks for all the helpful information! I'll be digging deeper into this issue soon to see what I can find out.

**Comment by MCOfficer** [comment]
Lemme add even more information. 

I don't think that this is an issue with my code, but for full clarity here's the entire scope as of now:

```rust
pub fn bulk_request(opt: &Opt, body: BulkBody) -> Result<()> {
    let response = isahc::http::Request::put(format!("{}/links/_bulk", opt.elastic_url))
        .header(CONTENT_TYPE, "application/json")
        .authentication(Authentication::basic())
        .credentials(Credentials::new("elastic", opt.elastic_pass.clone()))
        .body(body.to_string())?
        .send()?;
    if !response.status().is_success() {
        dbg!(&response.status().as_str());
        dbg!(&response.headers());
        let mut buffer = String::new();
        response.into_body().read_to_string(&mut buffer)?;
        error!("Got non-success status code, response was\n {}", buffer);
    }
    Ok(())
}
```

The reason i believe this are the dbg!'s I added: I get no output from them even when i get this warning - so it doesn't have anything to do with the if statement, and after the if there's nothing that would use the body. 

I will update to 0.9.14 and see if i can reproduce it there.

**Comment by sagebind** [comment]
Thanks for the additional info. I'm hoping to dig deeper into this problem soon. My hunch is that there is a race condition of some sort somewhere with low probability of occurring causing the response stream to be dropped early.

**Comment by sagebind** [comment]
OK, so I did some digging just to verify, but I'm not seeing any bugs like this in Isahc. However, I did notice something about your code after reading it again -- you only consume the response body if the response code is _not_ a 2xx. This is probably the source of the warning, as you are not consuming the response body in the success case.

Now the warning is probably rare for you because the response body in this case may be very small, in which case there's a good chance that it will have been read already as part of the same read operation that read the response headers, so therefore no problem. But this can vary a lot since the amount returned in a read can vary depending on hardware state, network conditions, and just other things the kernel is working on. I bet in the rare circumstance where the body is not fully read before `send()` returns to your code is when you are getting this warning. I bet if the server returned a larger response body (>16 KiB, our default read buffer size) you would get this warning for every request.

The way to avoid this is to make sure you always consume the response body. For example,

```rust
pub fn bulk_request(opt: &Opt, body: BulkBody) -> Result<()> {
    let mut response = isahc::http::Request::put(format!("{}/links/_bulk", opt.elastic_url))
        .header(CONTENT_TYPE, "application/json")
        .authentication(Authentication::basic())
        .credentials(Credentials::new("elastic", opt.elastic_pass.clone()))
        .body(body.to_string())?
        .send()?;
    if !response.status().is_success() {
        dbg!(&response.status().as_str());
        dbg!(&response.headers());
        let mut buffer = String::new();
        response.into_body().read_to_string(&mut buffer)?;
        error!("Got non-success status code, response was\n {}", buffer);
    } else {
        // Always consume response body to allow connection reuse.
        response.copy_into(std::io::sink())?;
    }
    Ok(())
}
```

On my end, there's a couple things that we should do to make this a better experience for you:

- Improve the warning message to explain what is happening better, and include a suggestion in how to fix it.
- Call out this behavior more clearly in the documentation.
- Add methods as described in #257 to make it simple to do this consuming.

I considered having the response body do this on drop automatically, but decided against it as doing I/O for an unknown amount of time (e.g. very large bodies) inside a drop handler is not a wise move and can be an unexpected performance gotcha.

**Comment by MCOfficer** [comment]
> OK, so I did some digging just to verify, but I'm not seeing any bugs like this in Isahc. However, I did notice something about your code after reading it again -- you only consume the response body if the response code is _not_ a 2xx. This is probably the source of the warning, as you are not consuming the response body in the success case.
> 
> Now the warning is probably rare for you because the response body in this case may be very small, in which case there's a good chance that it will have been read already as part of the same read operation that read the response headers, so therefore no problem. But this can vary a lot since the amount returned in a read can vary depending on hardware state, network conditions, and just other things the kernel is working on. I bet in the rare circumstance where the body is not fully read before `send()` returns to your code is when you are getting this warning. I bet if the server returned a larger response body (>16 KiB, our default read buffer size) you would get this warning for every request.


I see, I did not expect `response.status()` to also (partially) read the body. I thought it would just be dropped without the response ever being turned *into* a body, which somehow wouldn't trigger the warning...? Now that you explained it, that doesn't make a lot of sense :sweat_smile: .


> 
> The way to avoid this is to make sure you always consume the response body. For example,
> 
> ```rust
> pub fn bulk_request(opt: &Opt, body: BulkBody) -> Result<()> {
>     let mut response = isahc::http::Request::put(format!("{}/links/_bulk", opt.elastic_url))
>         .header(CONTENT_TYPE, "application/json")
>         .authentication(Authentication::basic())
>         .credentials(Credentials::new("elastic", opt.elastic_pass.clone()))
>         .body(body.to_string())?
>         .send()?;
>     if !response.status().is_success() {
>         dbg!(&response.status().as_str());
>         dbg!(&response.headers());
>         let mut buffer = String::new();
>         response.into_body().read_to_string(&mut buffer)?;
>         error!("Got non-success status code, response was\n {}", buffer);
>     } else {
>         // Always consume response body to allow connection reuse.
>         response.copy_into(std::io::sink())?;
>     }
>     Ok(())
> }
> ```

I'll see if I can perform another test, but it sounds correct. 


> On my end, there's a couple things that we should do to make this a better experience for you:
> 
>     * Improve the warning message to explain what is happening better, and include a suggestion in how to fix it.
> 
>     * Call out this behavior more clearly in the documentation.
> 
>     * Add methods as described in #257 to make it simple to do this consuming.

More docs is always a thumbs up for me.



> I considered having the response body do this on drop automatically, but decided against it as doing I/O for an unknown amount of time (e.g. very large bodies) inside a drop handler is not a wise move and can be an unexpected performance gotcha.

I don't have a development environment at hand, so this is entirely off the top of my head. Assuming I receive a *very* large response body, would it be beneficial to allow some form of explicit drop instead, without triggering the warning? I'm thinking something like a `response.close_connection()`. I certainly wouldn't want to read several hundred MB just to get rid of a log.

**Comment by sagebind** [comment]
>I see, I did not expect `response.status()` to also (partially) read the body

`send()` does not return until at _least_ the response headers have been read. `status()` does not do any reading, it just returns the status code already read.

When HTTP/1.x is being used, there's no way to read _just_ the response headers because it is of an unknown size. You just fill the buffer and then look for the end of the header (`\r\n\r\n`). But more _may_ have been returned to you in the same `read()` call. Indeed, if the entire response headers and body fit inside one TCP packet, then there's a very good chance the whole thing will be read off the socket in a single `read()`.

> Assuming I receive a _very_ large response body, would it be beneficial to allow something akin to an explicit drop instead, without triggering the warning?

Yeah, that sounds pretty reasonable to include. Perhaps `abort()` would be a good method name. Though be aware that both `abort()` and `consume()` (if provided) have trade-offs. With HTTP/1.x, there's no facility in the protocol to tell the server, "Hey, I know I asked for this big file and you're doing a great job sending it to me, but could you _stop_?" Your only option is to ungracefully close the TCP connection.

In applications doing file downloads, this is probably what you want if you click "Cancel", but in applications making many small API calls, this is probably _not_ what you want. If the response body is just a few MB, then it is probably more efficient in the long run to simply read the response and throw it away rather than take a hit on connection reuse by closing the connection. Establishing new connections can be pretty expensive, relatively speaking.

As I write this, I am warming to the idea of providing both `consume()` _and_ `abort()`, with appropriate docs on each about their tradeoffs.

Note that if you _know_ you are using HTTP/2 or newer, then `abort()` would probably be better since HTTP/2 does include throttle controls as part of the protocol, which we already use proactively. (Meaning, if a buffer of response body is sitting there waiting to be read for a while and you do not immediately read it, we already ask the server to stop sending more data until we know you want to continue.) Aborting one transfer does not prevent you from reusing an HTTP/2 connection.

**Comment by sagebind** [comment]
Also while digging, I did just now find an issue (sort of a race condition) where we are emitting that warning inconsistently right now. Everything else works correctly, but the condition under which we emit the warning is a bit inconsistent. 😅 It should be emitted more often than it is right now...

**Comment by MCOfficer** [comment]
Thank you for your elaborate responses, I'm really enjoying this sort of in-depth knowledge :)


> In applications doing file downloads, this is probably what you want if you click "Cancel", but in applications making many small API calls, this is probably _not_ what you want. If the response body is just a few MB, then it is probably more efficient in the long run to simply read the response and throw it away rather than take a hit on connection reuse by closing the connection. Establishing new connections can be pretty expensive, relatively speaking.

Just for the record, this efficiency hit would only apply when querying the same server again, right? Querying different servers would require a new connection anyways.

> Also while digging, I did just now find an issue (sort of a race condition) where we are emitting that warning inconsistently right now. Everything else works correctly, but the condition under which we emit the warning is a bit inconsistent. 😅 It should be emitted more often than it is right now...

Glad I helped reveal that ^^

**Comment by sagebind** [comment]
> Just for the record, this efficiency hit would only apply when querying the same server again, right? Querying different servers would require a new connection anyways.

Yep, that's right, this is only a problem when making multiple requests to the same server. By default we cache everything for a short time since Isahc doesn't know if you are going to make more requests to the same server or not, though this can be changed with custom client configuration.

**Comment by sagebind** [comment]
Thinking about this further, I am having second thoughts as to whether this is the appropriate direction to go. While it isn't usually the most optimal way of performing requests, there is nothing inherently wrong with aborting connections early if you don't care about the response body, and connection pooling is never _guaranteed_ to be possible regardless. I suppose it is a trade-off between convenience and explicitness:

- **Explicit:** Have the caller choose whether they want to consume and discard the response, or abort it. Gives a good degree of control, but is more complicated to understand.
- **Convenient:** Same behavior as today, except just remove the warning altogether (make it an `INFO` or `DEBUG`). Simpler for everyone to grasp, but some users may be unintentionally leaving some performance on the table. Most HTTP clients appear to go with this approach.

Maybe changing the warning into an `INFO` or `DEBUG` message is a sufficient solution, as most users may not care about the difference and trade-offs of approach and would rather have the HTTP client just handle it. Users already looking to tune the performance of their code might be more interested in these distinctions and may decide to consume the response stream instead.

**Comment by sagebind** [comment]
I decided to change this log to an `INFO` level message instead and to make the message itself much more understandable (as well as fix the message being reported inconsistently). This change will be in the next release.
