### ISSUE TITLE
need add ci check 

### ISSUE THREAD

**Issue by baoyachi** [sagebind/isahc#274]
when ci running ,should add `cargo fmt`,`cargo fix`,`cargo clippy` check

**Comment by sagebind** [comment]
Configuration for rustfmt added in #276 and applied in #277. I'm not a fan of failing CI due to code style since it is trivial to apply ourselves; no need to increase the barrier to entry for potential contributors if avoidable. But also running `cargo fmt` every other commit is also annoying for contributors since you must pull before every new push. In addition, applying rustfmt _after_ merging just pollutes the Git history when it would it be better to be pre-formatted as part of a squash merge.

Because of these difficulties, as a compromise, I've added one manual step for running rustfmt. PR authors and repo maintainers can now mention a bot with `@teto-bot rustfmt` in a PR comment, and the bot will push a commit to the PR after running `cargo fmt` if there are any changes. We'll run with this for a while to see how it goes I think.

**Comment by sagebind** [comment]
Clippy added in #279.
