### ISSUE TITLE
Any easy way to Rate Limit?

### ISSUE THREAD

**Issue by akashgurava** [sagebind/isahc#302]
I am writing a REST Client for Webull API. On some testing I found that Instead of simultaneously sending all requests, sending a request at small interval(10ms) drastically improves execution time(1/3 of previous).

I am currently using tower for this rate limiting, since isahc already has good configurability, I was wondering may be you can add something like this?

https://gist.github.com/akashgurava/d20638686db13badccab5b1ec51a5ab5

**Comment by sagebind** [comment]
> On some testing I found that Instead of simultaneously sending all requests, sending a request at small interval(10ms) drastically improves execution time(1/3 of previous).

In Isahc, all requests go through an HTTP client. The free-standing functions create an implicit global client lazily. I suspect the times you are seeing is because when you send all requests at once, then all requests are waiting for the client to initialize. If you send the requests one after the other, then only the first request is waiting for the client to initialize.

If you want to initialize a client beforehand, I recommend creating your own [`HttpClient`](https://docs.rs/isahc/1.1.0/isahc/struct.HttpClient.html) instance so that the client initialization isn't included in your benchmark.

As far as rate limiting, I think that would be out of scope for Isahc to include, though it would be a good use case for [interceptors](https://docs.rs/isahc/1.1.0/isahc/index.html#unstable-interceptors) which are currently unstable (#247).

**Comment by akashgurava** [comment]
I am already using the client. I will check to see how I can leverage interceptors. Thank you.
