### ISSUE TITLE
is any plan add json_pretty method ?

### ISSUE THREAD

**Issue by baoyachi** [sagebind/isahc#306]
## json 
* [json.rs](https://github.com/sagebind/isahc/blob/master/examples/json.rs)
```rust
       let json = Request::post(url)
        .header("Content-Type", "application/json")
        .timeout(Duration::from_secs(timeout))
        .body(body)?
        .send()?
        .json::<serde_json::Value>()?;
```
Serialize the given data structure as a pretty-printed String of JSON.

like this:

```rust
       let json = Request::post(url)
        .header("Content-Type", "application/json")
        .timeout(Duration::from_secs(timeout))
        .body(body)?
        .send()?
        .json_pretty:<serde_json::Value>()?;
```

**Comment by sagebind** [comment]
I'm not sure I understand what is being proposed here. In this example, the `json` method is _de-serializing_ the response body from the server into the desired type, so a `json_pretty` here wouldn't make sense since one method can de-serialize both pretty and compact JSON equivalently.

Isahc doesn't provide any convenience methods right now for serializing the request body, but you can probably use [`to_vec_pretty`](https://docs.rs/serde_json/1.0.62/serde_json/fn.to_vec_pretty.html) from serde_json to do that.
