### ISSUE TITLE
Tracking changes

### ISSUE THREAD

**Issue by ayrat555** [sagebind/isahc#326]
It seems it's not possible to track changes between different versions of the library.

Solution: track changes in the CHANGELOG file

**Comment by ayrat555** [comment]
Oh. I see that changes are on the Github releases page. But I think it would be nice to have them in the CHANGELOG file.

**Comment by sagebind** [comment]
Thanks for your question! I do indeed keep a detailed changelog in the GitHub releases page with the details of each version, which you can view [here](https://github.com/sagebind/isahc/releases). I don't use `CHANGELOG` files since I already keep the notes in the GitHub releases page, and keeping them in two places increases effort to ensure the two would be in sync and not drift apart. I do agree that keeping a detailed changelog is important and very helpful to users, which is why I do it.

Thanks for the suggestion anyway!
