### ISSUE TITLE
SSL connect error code: 35

### ISSUE THREAD

**Issue by mamcx** [sagebind/isahc#332]
I update a utility that was working fine, but then getting in a few machines this error `(SSL connect error code: 35) `and was unable to see what could have caused it.

I tried compiling everything statically (the first was the past version and the second is upgrade):

```
isahc = { version = "0.9.13", features = ["static-ssl", "static-curl", "text-decoding", "http2", "json", "cookies"] } 
isahc = { version = "1.4.0", features = ["static-ssl", "static-curl", "text-decoding", "http2", "json", "cookies"] } 
```
The affected machines are all windows server r2. How can I diagnose this?

**Comment by sagebind** [comment]
Thanks for filing an issue! This definitely should not be the case, so something must be going wrong here. At the very least, `SSL connect error code: 35` is a really poor error message! Let's see if we can get to the bottom of this.

First, if you have a larger error string or panic message, its always helpful to include that so that we can see more context.

Second, could you share how you are configuring your HTTP requests? And, if you're using a custom `HttpClient` instance, please share how you've configured that as well. That will help identify if the issue could be related to a particular configuration.

Thirdly, you can get a lot more debugging information if you capture the log output on the `isahc` logging target. If you don't have a [`log`](https://crates.io/crates/log)-compatible logger already, you can capture this using a logger like [`env_logger`](https://crates.io/crates/env_logger) and then setting an environment variable before running your utility: `RUST_LOG=isahc=debug`. This will print out lots of useful information, particularly around SSL which we are interested in. If you could share that here (first sanitizing any sensitive data you might have of course) then that would probably be the biggest help in identifying the problem.

My gut reaction is that this might be a regression in the curl VTLS engine on Windows, but I can't be confident of anything yet! There's no changes to Isahc's default SSL configuration between 0.9.x and 1.x that I recall.

**Comment by mamcx** [comment]
Is super-weird, the RUST_BACKTRACE=1 does not work on that windows (?), so the only thing I get is the same error.

Other enterprise software made by _another_ company in .NET/SQL Server also gets hit by an SSL error.

I try to extract a minimal sample with the same code (bellow) and it does not trigger the bug, which makes me flip :). Our customers were desperate so I replace isahc with ureq (hail static types and easy refactorings with Rust!):

`ureq = { version = "2.1.1", features = ["default", "json", "charset", "cookies"] }

And it works. 

This is likely a very freaky bug so our workaround works for us so far. I think close the issue and just put it here in case other people get affected and we can get more info...

P.D: The site SSL was from cloudflare. The code to call it was:

```rust
use isahc::prelude::*;
use std::time::Duration;
use isahc::{HttpClient, HttpClientBuilder, Response, Body};
use isahc::auth::Authentication;
use isahc::http::request::Builder;
use isahc::Request;
use serde::{Serialize, Deserialize};
use isahc::config::{SslOption, CaCertificate};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LoginRow {
    pub company: String,
    pub user_name: String,
    pub password: String,
    pub client_id: String,
}

impl LoginRow {
    pub fn new() -> Self {
        LoginRow {
            company: "_sync".to_string(),
            user_name: "abc".into(),
            password: "12345678".into(),
            client_id: "Web".to_string(),
        }
    }

    pub fn new_user_auto(company: &str, user: &str) -> Self {
        LoginRow {
            company: company.to_string(),
            user_name: user.to_string(),
            password: "".to_string(),
            client_id: "Web".to_string(),
        }
    }
}

pub fn build_client(timeout: u64) -> HttpClientBuilder {
    let timeout = Duration::from_secs(timeout);

    HttpClient::builder().timeout(timeout).cookies()
}

pub fn build_request( headers: &[(&str, &str)], url: &str, agent: &str) -> Builder {
    let mut req = Request::builder()
        .header("Accept-Encoding", "gzip, deflate")
        .header("User-Agent", agent)
        .ssl_ca_certificate(CaCertificate::file("curl-ca-bundle.crt")) //try with same from Curl, not change on bug
        .authentication(Authentication::all());

    for (name, value) in headers {
        req = req.header(*name, *value);
    }

    req.method("POST")
        .timeout(Duration::from_secs(60 * 5))
        .uri(url)
}

pub fn fetch<B>(
    client: &HttpClient,
    url: &str,

    headers: &[(&str, &str)],
    body: &B,
) -> Result<Response<Body>, isahc::Error>
    where
        B: Serialize + core::fmt::Debug,
{
    let mut body = serde_json::to_vec(&body).unwrap();
    // Hack for a customer that don't accept a body on GET (this is called with '()')
    if body == [110, 117, 108, 108] {
        body.clear();
    }

    let response = build_request( headers, url, "Sync/1.0").body(body)?;
    let response = client.send(response)?;

    Ok(response)
}


fn isaac() -> Result<(), isahc::Error> {
    let client = build_client(10000 * 3).build()?;
    let headers = &[("content-type", "application/json")];
    let url ="https://???.???.net/v1/api/login"; //cloudflare serve this

    let login = LoginRow::new();
    let response = fetch(&client, url,  headers, &login)?;

    println!("Headers: {:#?}", response.headers());
    println!("Status: {}", response.status());


    Ok(())
}

fn main() -> Result<(), bool> {
    isaac().map_err(|e| {
        eprintln!("{}", e);
        false
    })
}
```

**Comment by sagebind** [comment]
I don't want to put undue pressure on you if you don't have the time to help (if not that's OK) but I'd still like to get to the bottom of this and discover the root cause if possible and see if there's something we can do about this from Isahc.

A possible reason ureq worked is that it uses rustls as the SSL engine instead of the operating system's SSL engine, so I suspect that's where things are going astray. It could be that the SSL settings configured in the operating system isn't correct, or certificates aren't quite configured right, or something along that nature.

Using `env_logger` and `RUST_LOG` is definitely the way to go here to capture more troubleshooting information. In it the logs will state explicitly what SSL engine is being used and how it is being initialized.

(I'm sad to see you go, but ureq is a good library too.)
