### ISSUE TITLE
Rename native-tls feature

### ISSUE THREAD

**Issue by 89z** [sagebind/isahc#410]
Currently one feature is called native-tls:

https://github.com/sagebind/isahc/blob/7163e8ab8b4bb86893ed8d95e977eeba797be601/Cargo.toml#L21-L26

This is pretty misleading, as an actual native-tls crate is available:

https://crates.io/crates/native-tls

plus, the native-tls crate actually does what is says, for example, it uses Schannel on Windows, to avoid OpenSSL or other TLS options. The "native-tls" feature here doesnt do that.

**Comment by 89z** [comment]
https://github.com/sagebind/isahc/issues/199

**Comment by sagebind** [comment]
Thanks for opening an issue. I'm not exactly sure why this is a problematic name though, maybe you could explain more?

- Is there a technical problem with using the name `native-tls` as the feature name? I thought they were in separate "namespaces" as dependency names. Even so, we don't depend on the actual `native-tls` crate (and probably never will). I could see how that might be confusing, but at the end of the day as long as the feature uses the platform's native TLS one way or another is that fine?
- The feature does in fact use the platform's native TLS where possible. It enables the [`ssl` feature in the curl crate](https://github.com/alexcrichton/curl-rust#building), which by default will configure libcurl to use whatever TLS library is considered "native" (schannel on Windows, SecureTransport on macOS, OpenSSL otherwise). Note that if Isahc/curl is configured to use a system-wide installation of libcurl, this won't have effect as whatever TLS the system-wide libcurl was built with will be used.

**Comment by 89z** [comment]
You make some good arguments. I am going to close this, but it seems `isahc` is still not a good fit for me. The current dep count of this package is 57 from my count, which is way over what I would want to see for something like this. I think using `native-tls` directly, or `rustls` as mentioned in the other issue could help lower the dep count. I guess I will wait until that issue is resolved. Thanks.

**Comment by sagebind** [comment]
Sorry to see you go, but to be fair Isahc isn't for everyone and isn't the best tool for all jobs.

> The current dep count of this package is 57 from my count, which is way over what I would want to see for something like this.

You might be hard-pressed to find too many HTTP clients smaller than this count (I'm guessing you are counting transitive dependencies?) as modern HTTP is deceptively complex stack.

> I think using `native-tls` directly, or `rustls` as mentioned in the other issue could help lower the dep count.

Isahc actually can't use the `native-tls` crate, we can only use SSL engines that libcurl supports under the hood. Which libcurl already supports "native TLS" libraries for most platforms, though it implements that itself and does not need a `native-tls` crate to do so.

Rustls support will be coming in version 2.0 this or next year, but it will probably result in more dependencies and not less (it will be opt-in though). If number of dependencies matters that much to you, then your best bet might be [ureq](https://github.com/algesten/ureq) with ~30 dependencies.

**Comment by 89z** [comment]
> You might be hard-pressed to find too many HTTP clients smaller than this count (I'm guessing you are counting transitive dependencies?) as modern HTTP is a deceptively complex stack.

I found quite a few:

deps | crate
-----|------
41   | `ehttp`
29   | `rttp_client`
17   | `lynx`
15   | `attohttpc`
14   | `ureq`
11   | `oxhttp`

something weird I have noticed about the Rust community, people seem to think the crate world is smaller than it actually is. To be fair, part of that is the awful search on crates.io [1]. At any rate, good crates are available for different needs, if people are willing to spend the time looking.

1. https://github.com/rust-lang/crates.io/issues/5222

**Comment by sagebind** [comment]
Really curious how you got those dependency counts, is there a tool that I should be using to get those? It would be really helpful!

Does this include transitive dependencies or not? I mean if you only count direct, non-optional dependencies then Isahc only has 17.

My point wasn't to say that there aren't a lot of HTTP clients, my point was that most of them are going to have similar dependency counts. HTTP is hard and you'd have to be crazy (and not very practical) to try and implement the whole thing yourself without any dependencies.

**Comment by 89z** [comment]
> Really curious how you got those dependency counts, is there a tool that I should be using to get those? It would be really helpful!
> 
> Does this include transitive dependencies or not? I mean if you only count direct, non-optional dependencies then Isahc only has 17.

Its here [1]. By default it turns all features off, so essentially its the same as this:

~~~
cargo add --no-default-features isahc
cargo tree --prefix none
~~~

which results in 54 unique crates (including isahc itself) at the time of this comment.

1. https://github.com/89z/piccolo/tree/v1.5.8/cmd/rust-deps

> My point wasn't to say that there aren't a lot of HTTP clients, my point was that most of them are going to have similar dependency counts. HTTP is hard and you'd have to be crazy (and not very practical) to try and implement the whole thing yourself without any dependencies.

With all due respect, I think you are hand-waving away some pretty big differences, that I have already pointed out. Some of the crates I listed have less than half the dependencies of Isahc. I understand thats not the only metric that matters, but its important to me.

**Comment by sagebind** [comment]
Ah, OK I see how you are counting now. At least I have a frame of reference for the numbers, thanks for sharing.

I like to think that every single Isahc dependency has been carefully curated and chosen, and serves a very specific and important purpose, but I also don't always get it right. Isahc has had several very deliberate dependency pruning efforts over the years to trim things down to only what could be considered essential, and maybe we can do that again this year as the landscape continually changes.

Most of that dependency count comes from transitive dependencies, which I can't do much about besides maybe choosing a different alternative dependency, but I'd only do so if the transitive count seems egregious to me, or if an alternative is better anyway. I don't usually avoid using the right tool for the job just because of its dependency count, but I have swapped out for "worse" libraries on occasion, if the one I was using compiles very slowly or is very large.

Unfortunately the two biggest offenders for pulling in transitive dependencies I can't do much about: `curl`, which pulls in a number of things, but by design Isahc is a curl wrapper so I can't really get rid of that, and `tracing`, which I'm not using "just to use" but rather make Isahc compatible with a particular ecosystem. Even so, we are considering making `tracing` an optional dependency: https://github.com/sagebind/isahc/issues/293.

That's OK though if we value dependencies differently, and if Isahc isn't acceptable to you then that's OK. For me every dependency must have a justification for being there, and none are free from being re-evaluated. But so long as I've done that, the total count doesn't matter to me that much. I'd definitely almost never consider sacrificing something like runtime performance in order to reduce dependency count, nor try to re-implement something that already exists unless it is either small, or I know I can do it better or more tailored for Isahc's use case.
