### ISSUE TITLE
chttp cannot be compiled under arch linux.

### ISSUE THREAD

**Issue by NikosEfthias** [sagebind/isahc#44]
I have openssl installed and both `libssl.so.1.1` and `libssl.so.1.0.0` under `/usr/lib` folder
[here](https://github.com/NikosEfthias/chttp_bug) is the demo project to replicate the problem.
When i compile this in a docker container with ubuntu it compiles however in arch linux which is my only os installed i cannot compile it 
![image](https://user-images.githubusercontent.com/9097437/61142462-7b4c4d00-a4d8-11e9-80a3-18b5c4dc7396.png)

**Comment by sagebind** [comment]
Hmm, I have been hearing about various issues compiling with OpenSSL under some distros. Since the error message references the `psl` crate, try compiling again with the `psl` feature disabled and let me know if you get any farther. I'll get a Docker image based on Arch set up as a test case.

If this _is_ somehow caused by the psl crate, then you might be glad to hear that this will no longer be a dependency in the next chttp version. (This wouldn't be the first problem it has caused.)

**Comment by NikosEfthias** [comment]
could you please guide me through how to disable the `psl` feature @sagebind ?

**Comment by sagebind** [comment]
I have not been able to reproduce this so far. I spun up a Docker container using the archlinux/base image, installed both `openssl` and `openssl-1.0` packages, and compiled the linked example with no trouble (other than fixing a missing semicolon in `main.rs`).

**Comment by sagebind** [comment]
`psl` is no longer a dependency, so I am assuming that this is no longer a problem.
