### ISSUE TITLE
Support username / password and CURLOPT_HTTPAUTH settings.

### ISSUE THREAD

**Issue by kathampy** [sagebind/isahc#84]
Seems like an oversight that username / password is not supported at all.

**Comment by sagebind** [comment]
Technically you could set an `Authorization` header yourself manually on your request, but I agree exposing a higher-level interface would be useful.

Since this is a higher thing than the HTTP protocol itself, I wonder if there is any client auth middleware for the `http` crate that accomplishes the same thing.

**Comment by kathampy** [comment]
I think it should be passed through to `curl` because I believe something like `CURLAUTH_NTLM` or `CURLAUTH_NEGOTIATE` requires multiple automatic exchanges.

**Comment by abatkin** [comment]
Sort-of related: I would be interested in support for Negotiate, since libcurl already has native support. Maybe it's worth exposing (or wrapping) the [Auth](https://docs.rs/curl/0.4.25/curl/easy/struct.Auth.html) struct. Primarily I would like this for requests, but libcurl also supports proxy auth, which would be nice too.

I might be able to take a stab at this, but I would want to get agreement on what the API should look like first (and that such a feature would be acceptable).

**Comment by sagebind** [comment]
I have a pull request (work in progress) in process for this here: https://github.com/sagebind/isahc/pull/115
