### ISSUE TITLE
Use `Request.version()`  instead of `preferred_http_version()`.

### ISSUE THREAD

**Issue by kathampy** [sagebind/isahc#94]
The response has the HTTP version populated into `Response.version()`. `Request` should probably be consistent with this, even if `HttpClient` uses `preferred_http_version()`. I was accidentally setting `Request.version()` to no effect.

The documentation for `Response` from the `http` crate says the default version is HTTP/1.1, but I assume `isahc` uses `CURL_HTTP_VERSION_NONE`.

Please expose `CURL_HTTP_VERSION_2_PRIOR_KNOWLEDGE` as well. I don't think `CURL_HTTP_VERSION_2TLS` makes sense.

**Comment by sagebind** [comment]
The problem with that is that `http::Version::default()` returns `http::Version::HTTP_11`, so if we looked at the `version` field on the request in order to determine which version to prefer, we'd always be defaulting to HTTP/1.1 instead of HTTP/2 unless the user knew better to set it to 2 manually. An `http::Request` _always_ has a specific version associated with it. I believe the primary use-case for the `version` field is for _incoming_ HTTP requests, not _outgoing_ HTTP requests.

`preferred_http_version()` uses a totally separate field for this reason, so that the default is actually `None` and then Isahc can internally pick a better default.

I can certainly improve the documentation around this if nothing else.

**Comment by kathampy** [comment]
What about using your own `Enum` for setting the HTTP version? It would be a breaking change but you can support `CURL_HTTP_VERSION_2_PRIOR_KNOWLEDGE` for `h2c` connections.

**Comment by sagebind** [comment]
Switching to `CURL_HTTP_VERSION_2_PRIOR_KNOWLEDGE` could also be a separate option.

> Since you already decided that `isahc` will only ever use `libcurl`, trying to restrict all HTTP layer stuff to the `http` crate doesn't serve any purpose and just limits `curl` functionality.

My goal is not necessarily to expose all curl functionality, though exposing useful features is on the roadmap. My primary goal with Isahc is to carefully and incrementally build the best client API possible that is easy to understand and use, which often doesn't line up 1-to-1 with curl's API. Backwards compatibility is very important to me, which is why am generally over-cautious about carefully thinking out the best design, instead of over-eagerly exposing everything curl supports.

As much as I like the curl project, there's some things in there that are very awkward to use, but have not changed because an appreciable adherence to backwards compatability. I hope Isahc can provide that same kind of guarantee if possible, but have its API start from a better place than curl.

**Comment by sagebind** [comment]
I've decided to close this issue, as the original ask (respecting `Request::version`) isn't something I want to do for the reason that the default value of this field (`HTTP_11`) conflicts with our desire to default to HTTP/2.

For supporting HTTP/2 Prior Knowledge I opened a separate issue: https://github.com/sagebind/isahc/issues/108

Let me know if you have any other questions or concerns.
